//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 01:16:42 AM IST 
//


package com.wellpoint.sales.eox.poc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wellpoint.sales.eox.poc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Contents_QNAME = new QName("http://wellpoint.com/sales/eox/poc", "contents");
    private final static QName _Vendor_QNAME = new QName("http://wellpoint.com/sales/eox/poc", "vendor");
    private final static QName _Content_QNAME = new QName("http://wellpoint.com/sales/eox/poc", "content");
    private final static QName _ContentID_QNAME = new QName("http://wellpoint.com/sales/eox/poc", "contentID");
    private final static QName _State_QNAME = new QName("http://wellpoint.com/sales/eox/poc", "state");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wellpoint.sales.eox.poc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

    /**
     * Create an instance of {@link ContentsType }
     * 
     */
    public ContentsType createContentsType() {
        return new ContentsType();
    }

    /**
     * Create an instance of {@link ContentIDType }
     * 
     */
    public ContentIDType createContentIDType() {
        return new ContentIDType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wellpoint.com/sales/eox/poc", name = "contents")
    public JAXBElement<ContentsType> createContents(ContentsType value) {
        return new JAXBElement<ContentsType>(_Contents_QNAME, ContentsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wellpoint.com/sales/eox/poc", name = "vendor")
    public JAXBElement<String> createVendor(String value) {
        return new JAXBElement<String>(_Vendor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wellpoint.com/sales/eox/poc", name = "content")
    public JAXBElement<ContentType> createContent(ContentType value) {
        return new JAXBElement<ContentType>(_Content_QNAME, ContentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wellpoint.com/sales/eox/poc", name = "contentID")
    public JAXBElement<ContentIDType> createContentID(ContentIDType value) {
        return new JAXBElement<ContentIDType>(_ContentID_QNAME, ContentIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wellpoint.com/sales/eox/poc", name = "state")
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

}
