//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 01:16:42 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://wellpoint.com/sales/eox/poc", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.wellpoint.sales.eox.poc;
